DROP TABLE IF EXISTS roles_permissions_test;
DROP TABLE IF EXISTS user_roles_test;
DROP TABLE IF EXISTS permissions_test;
DROP TABLE IF EXISTS roles_test;

DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS response;
DROP TABLE IF EXISTS request;
DROP TABLE IF EXISTS paciente;
DROP TABLE IF EXISTS invitaciones;
DROP TABLE IF EXISTS medico;
DROP TABLE IF EXISTS hospital;
DROP TABLE IF EXISTS user;
